// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FETCHING = 'LOGIN_FETCHING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
// FORGOT PASSWORD
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_FETCHING = 'FORGOT_PASSWORD_FETCHING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';
// RESET PASSWORD
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_FETCHING = 'RESET_PASSWORD_FETCHING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
// REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FETCHING = 'REGISTER_FETCHING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
// UPDATA PASSWORD
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_FETCHING = 'UPDATE_PASSWORD_FETCHING';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';
// SCHOOL
export const ADD_SCHOOL_REQUEST = 'ADD_SCHOOL_REQUEST';
export const ADD_SCHOOL_FETCHING = 'ADD_SCHOOL_FETCHING';
export const ADD_SCHOOL_SUCCESS = 'ADD_SCHOOL_SUCCESS';
export const ADD_SCHOOL_FAILED = 'ADD_SCHOOL_FAILED';
export const GET_SCHOOL_REQUEST = 'GET_SCHOOL_REQUEST';
export const GET_SCHOOL_FETCHING = 'GET_SCHOOL_FETCHING';
export const GET_SCHOOL_SUCCESS = 'GET_SCHOOL_SUCCESS';
export const GET_SCHOOL_FAILED = 'GET_SCHOOL_FAILED';
export const UPDATE_SCHOOL_REQUEST = 'UPDATE_SCHOOL_REQUEST';
export const UPDATE_SCHOOL_FETCHING = 'UPDATE_SCHOOL_FETCHING';
export const UPDATE_SCHOOL_SUCCESS = 'UPDATE_SCHOOL_SUCCESS';
export const UPDATE_SCHOOL_FAILED = 'UPDATE_SCHOOL_FAILED';
export const DELETE_SCHOOL_REQUEST = 'DELETE_SCHOOL_REQUEST';
export const DELETE_SCHOOL_FETCHING = 'DELETE_SCHOOL_FETCHING';
export const DELETE_SCHOOL_SUCCESS = 'DELETE_SCHOOL_SUCCESS';
export const DELETE_SCHOOL_FAILED = 'DELETE_SCHOOL_FAILED';
// MORE SCHOOL
export const ADD_MORE_SCHOOL_REQUEST = 'ADD_MORE_SCHOOL_REQUEST';
export const ADD_MORE_SCHOOL_FETCHING = 'ADD_MORE_SCHOOL_FETCHING';
export const ADD_MORE_SCHOOL_SUCCESS = 'ADD_MORE_SCHOOL_SUCCESS';
export const ADD_MORE_SCHOOL_FAILED = 'ADD_MORE_SCHOOL_FAILED';
// ACTIVITY
export const ADD_ACTIVITY_REQUEST = 'ADD_ACTIVITY_REQUEST';
export const ADD_ACTIVITY_FETCHING = 'ADD_ACTIVITY_FETCHING';
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS';
export const ADD_ACTIVITY_FAILED = 'ADD_ACTIVITY_FAILED';
export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST';
export const GET_ACTIVITY_FETCHING = 'GET_ACTIVITY_FETCHING';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_FAILED = 'GET_ACTIVITY_FAILED';
export const GET_ACTIVITY_BY_ID_REQUEST = 'GET_ACTIVITY_BY_ID_REQUEST';
export const GET_ACTIVITY_BY_ID_FETCHING = 'GET_ACTIVITY_BY_ID_FETCHING';
export const GET_ACTIVITY_BY_ID_SUCCESS = 'GET_ACTIVITY_BY_ID_SUCCESS';
export const GET_ACTIVITY_BY_ID_FAILED = 'GET_ACTIVITY_BY_ID_REQUEST';
export const GET_ACTIVITY_BY_ADMIN_ID_REQUEST = 'GET_ACTIVITY_BY_ADMIN_ID_REQUEST';
export const GET_ACTIVITY_BY_ADMIN_ID_FETCHING = 'GET_ACTIVITY_BY_ADMIN_ID_FETCHING';
export const GET_ACTIVITY_BY_ADMIN_ID_SUCCESS = 'GET_ACTIVITY_BY_ADMIN_ID_SUCCESS';
export const GET_ACTIVITY_BY_ADMIN_ID_FAILED = 'GET_ACTIVITY_BY_ADMIN_ID_FAILED';
export const UPDATE_ACTIVITY_REQUEST = 'UPDATE_ACTIVITY_REQUEST';
export const UPDATE_ACTIVITY_FETCHING = 'UPDATE_ACTIVITY_FETCHING';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
export const UPDATE_ACTIVITY_FAILED = 'UPDATE_ACTIVITY_FAILED';
export const DELETE_ACTIVITY_REQUEST = 'DELETE_ACTIVITY_REQUEST';
export const DELETE_ACTIVITY_FETCHING = 'DELETE_ACTIVITY_FETCHING';
export const DELETE_ACTIVITY_SUCCESS = 'DELETE_ACTIVITY_SUCCESS';
export const DELETE_ACTIVITY_FAILED = 'DELETE_ACTIVITY_FAILED';
// ACTIVITY LEVEL
export const ADD_ACTIVITY_LEVEL_REQUEST = 'ADD_ACTIVITY_LEVEL_REQUEST';
export const ADD_ACTIVITY_LEVEL_FETCHING = 'ADD_ACTIVITY_LEVEL_FETCHING';
export const ADD_ACTIVITY_LEVEL_SUCCESS = 'ADD_ACTIVITY_LEVEL_SUCCESS';
export const ADD_ACTIVITY_LEVEL_FAILED = 'ADD_ACTIVITY_LEVEL_FAILED';
export const GET_ACTIVITY_LEVEL_REQUEST = 'GET_ACTIVITY_LEVEL_REQUEST';
export const GET_ACTIVITY_LEVEL_FETCHING = 'GET_ACTIVITY_LEVEL_FETCHING';
export const GET_ACTIVITY_LEVEL_SUCCESS = 'GET_ACTIVITY_LEVEL_SUCCESS';
export const GET_ACTIVITY_LEVEL_FAILED = 'GET_ACTIVITY_LEVEL_FAILED';
export const GET_ACTIVITY_LEVEL_BY_ID_REQUEST = 'GET_ACTIVITY_LEVEL_BY_ID_REQUEST';
export const GET_ACTIVITY_LEVEL_BY_ID_FETCHING = 'GET_ACTIVITY_LEVEL_BY_ID_FETCHING';
export const GET_ACTIVITY_LEVEL_BY_ID_SUCCESS = 'GET_ACTIVITY_LEVEL_BY_ID_SUCCESS';
export const GET_ACTIVITY_LEVEL_BY_ID_FAILED = 'GET_ACTIVITY_LEVEL_BY_ID_FAILED';
export const UPDATE_ACTIVITY_LEVEL_REQUEST = 'UPDATE_ACTIVITY_LEVEL_REQUEST';
export const UPDATE_ACTIVITY_LEVEL_FETCHING = 'UPDATE_ACTIVITY_LEVEL_FETCHING';
export const UPDATE_ACTIVITY_LEVEL_SUCCESS = 'UPDATE_ACTIVITY_LEVEL_SUCCESS';
export const UPDATE_ACTIVITY_LEVEL_FAILED = 'UPDATE_ACTIVITY_LEVEL_FAILED';
export const DELETE_ACTIVITY_LEVEL_REQUEST = 'DELETE_ACTIVITY_LEVEL_REQUEST';
export const DELETE_ACTIVITY_LEVEL_FETCHING = 'DELETE_ACTIVITY_LEVEL_FETCHING';
export const DELETE_ACTIVITY_LEVEL_SUCCESS = 'DELETE_ACTIVITY_LEVEL_SUCCESS';
export const DELETE_ACTIVITY_LEVEL_FAILED = 'DELETE_ACTIVITY_LEVEL_FAILED';
// PROGRAM
export const ADD_PROGRAM_REQUEST = 'ADD_PROGRAM_REQUEST';
export const ADD_PROGRAM_FETCHING = 'ADD_PROGRAM_FETCHING';
export const ADD_PROGRAM_SUCCESS = 'ADD_PROGRAM_SUCCESS';
export const ADD_PROGRAM_FAILED = 'ADD_PROGRAM_FAILED';
export const GET_PROGRAM_REQUEST = 'GET_PROGRAM_REQUEST';
export const GET_PROGRAM_FETCHING = 'GET_PROGRAM_FETCHING';
export const GET_PROGRAM_SUCCESS = 'GET_PROGRAM_SUCCESS';
export const GET_PROGRAM_FAILED = 'GET_PROGRAM_FAILED';
export const GET_PROGRAM_BY_ID_REQUEST = 'GET_PROGRAM_BY_ID_REQUEST';
export const GET_PROGRAM_BY_ID_FETCHING = 'GET_PROGRAM_BY_ID_FETCHING';
export const GET_PROGRAM_BY_ID_SUCCESS = 'GET_PROGRAM_BY_ID_SUCCESS';
export const GET_PROGRAM_BY_ID_FAILED = 'GET_PROGRAM_BY_ID_FAILED';
export const GET_PROGRAM_BY_ADMIN_ID_REQUEST = 'GET_PROGRAM_BY_ADMIN_ID_REQUEST';
export const GET_PROGRAM_BY_ADMIN_ID_FETCHING = 'GET_PROGRAM_BY_ADMIN_ID_FETCHING';
export const GET_PROGRAM_BY_ADMIN_ID_SUCCESS = 'GET_PROGRAM_BY_ADMIN_ID_SUCCESS';
export const GET_PROGRAM_BY_ADMIN_ID_FAILED = 'GET_PROGRAM_BY_ADMIN_ID_FAILED';
export const GET_PROGRAM_DETAIL_BY_ACTIVITY_ID_REQUEST =
  'GET_PROGRAM_DETAIL_BY_ACTIVITY_ID_REQUEST';
export const GET_PROGRAM_DETAIL_BY_ACTIVITY_ID_FETCHING =
  'GET_PROGRAM_DETAIL_BY_ACTIVITY_ID_FETCHING';
export const GET_PROGRAM_DETAIL_BY_ACTIVITY_ID_SUCCESS =
  'GET_PROGRAM_DETAIL_BY_ACTIVITY_ID_SUCCESS';
export const GET_PROGRAM_DETAIL_BY_ACTIVITY_ID_FAILED = 'GET_PROGRAM_DETAIL_BY_ACTIVITY_ID_FAILED';
export const UPDATE_PROGRAM_REQUEST = 'UPDATE_PROGRAM_REQUEST';
export const UPDATE_PROGRAM_FETCHING = 'UPDATE_PROGRAM_FETCHING';
export const UPDATE_PROGRAM_SUCCESS = 'UPDATE_PROGRAM_SUCCESS';
export const UPDATE_PROGRAM_FAILED = 'UPDATE_PROGRAM_FAILED';
export const DELETE_PROGRAM_REQUEST = 'DELETE_PROGRAM_REQUEST';
export const DELETE_PROGRAM_FETCHING = 'DELETE_PROGRAM_FETCHING';
export const DELETE_PROGRAM_SUCCESS = 'DELETE_PROGRAM_SUCCESS';
export const DELETE_PROGRAM_FAILED = 'DELETE_PROGRAM_FAILED';
// ADMIN
export const ADD_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST';
export const ADD_ADMIN_FETCHING = 'ADD_ADMIN_FETCHING';
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';
export const ADD_ADMIN_FAILED = 'ADD_ADMIN_FAILED';
export const GET_ADMIN_REQUEST = 'GET_ADMIN_REQUEST';
export const GET_ADMIN_FETCHING = 'GET_ADMIN_FETCHING';
export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS';
export const GET_ADMIN_FAILED = 'GET_ADMIN_FAILED';
export const GET_ADMIN_BY_ID_REQUEST = 'GET_ADMIN_BY_ID_REQUEST';
export const GET_ADMIN_BY_ID_FETCHING = 'GET_ADMIN_BY_ID_FETCHING';
export const GET_ADMIN_BY_ID_SUCCESS = 'GET_ADMIN_BY_ID_SUCCESS';
export const GET_ADMIN_BY_ID_FAILED = 'GET_ADMIN_BY_ID_FAILED';
export const UPDATE_ADMIN_REQUEST = 'UPDATE_ADMIN_REQUEST';
export const UPDATE_ADMIN_FETCHING = 'UPDATE_ADMIN_FETCHING';
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS';
export const UPDATE_ADMIN_FAILED = 'UPDATE_ADMIN_FAILED';
export const DELETE_ADMIN_REQUEST = 'DELETE_ADMIN_REQUEST';
export const DELETE_ADMIN_FETCHING = 'DELETE_ADMIN_FETCHING';
export const DELETE_ADMIN_SUCCESS = 'DELETE_ADMIN_SUCCESS';
export const DELETE_ADMIN_FAILED = 'DELETE_ADMIN_FAILED';
// SITE
export const GET_SITE_REQUEST = 'GET_SITE_REQUEST';
export const GET_SITE_FETCHING = 'GET_SITE_FETCHING';
export const GET_SITE_SUCCESS = 'GET_SITE_SUCCESS';
export const GET_SITE_FAILED = 'GET_SITE_FAILED';
export const UPDATE_SITE_REQUEST = 'UPDATE_SITE_REQUEST';
export const UPDATE_SITE_FETCHING = 'UPDATE_SITE_FETCHING';
export const UPDATE_SITE_SUCCESS = 'UPDATE_SITE_SUCCESS';
export const UPDATE_SITE_FAILED = 'UPDATE_SITE_FAILED';
// NEWS
export const ADD_NEWS_REQUEST = 'ADD_NEWS_REQUEST';
export const ADD_NEWS_FETCHING = 'ADD_NEWS_FETCHING';
export const ADD_NEWS_SUCCESS = 'ADD_NEWS_SUCCESS';
export const ADD_NEWS_FAILED = 'ADD_NEWS_FAILED';
export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_FETCHING = 'GET_NEWS_FETCHING';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAILED = 'GET_NEWS_FAILED';
export const GET_NEWS_BY_ID_REQUEST = 'GET_NEWS_BY_ID_REQUEST';
export const GET_NEWS_BY_ID_FETCHING = 'GET_NEWS_BY_ID_FETCHING';
export const GET_NEWS_BY_ID_SUCCESS = 'GET_NEWS_BY_ID_SUCCESS';
export const GET_NEWS_BY_ID_FAILED = 'GET_NEWS_BY_ID_FAILED';
export const UPDATE_NEWS_REQUEST = 'UPDATE_NEWS_REQUEST';
export const UPDATE_NEWS_FETCHING = 'UPDATE_NEWS_FETCHING';
export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS';
export const UPDATE_NEWS_FAILED = 'UPDATE_NEWS_FAILED';
export const DELETE_NEWS_REQUEST = 'DELETE_NEWS_REQUEST';
export const DELETE_NEWS_FETCHING = 'DELETE_NEWS_FETCHING';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_FAILED = 'DELETE_NEWS_FAILED';
// MEMBER
export const ADD_MEMBER_REQUEST = 'ADD_MEMBER_REQUEST';
export const ADD_MEMBER_FETCHING = 'ADD_MEMBER_FETCHING';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_FAILED = 'ADD_MEMBER_FAILED';
export const GET_MEMBER_REQUEST = 'GET_MEMBER_REQUEST';
export const GET_MEMBER_FETCHING = 'GET_MEMBER_FETCHING';
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS';
export const GET_MEMBER_FAILED = 'GET_MEMBER_FAILED';
export const GET_MEMBER_BY_ID_REQUEST = 'GET_MEMBER_BY_ID_REQUEST';
export const GET_MEMBER_BY_ID_FETCHING = 'GET_MEMBER_BY_ID_FETCHING';
export const GET_MEMBER_BY_ID_SUCCESS = 'GET_MEMBER_BY_ID_SUCCESS';
export const GET_MEMBER_BY_ID_FAILED = 'GET_MEMBER_BY_ID_FAILED';
export const UPDATE_MEMBER_REQUEST = 'UPDATE_MEMBER_REQUEST';
export const UPDATE_MEMBER_FETCHING = 'UPDATE_MEMBER_FETCHING';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';
export const UPDATE_MEMBER_FAILED = 'UPDATE_MEMBER_FAILED';
export const DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST';
export const DELETE_MEMBER_FETCHING = 'DELETE_MEMBER_FETCHING';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_FAILED = 'DELETE_MEMBER_FAILED';
// AWARD_ATTACHMENT
export const ADD_AWARD_ATTACHMENT_REQUEST = 'ADD_AWARD_ATTACHMENT_REQUEST';
export const ADD_AWARD_ATTACHMENT_FETCHING = 'ADD_AWARD_ATTACHMENT_FETCHING';
export const ADD_AWARD_ATTACHMENT_SUCCESS = 'ADD_AWARD_ATTACHMENT_SUCCESS';
export const ADD_AWARD_ATTACHMENT_FAILED = 'ADD_AWARD_ATTACHMENT_FAILED';
export const GET_AWARD_ATTACHMENT_REQUEST = 'GET_AWARD_ATTACHMENT_REQUEST';
export const GET_AWARD_ATTACHMENT_FETCHING = 'GET_AWARD_ATTACHMENT_FETCHING';
export const GET_AWARD_ATTACHMENT_SUCCESS = 'GET_AWARD_ATTACHMENT_SUCCESS';
export const GET_AWARD_ATTACHMENT_FAILED = 'GET_AWARD_ATTACHMENT_FAILED';
export const GET_AWARD_ATTACHMENT_BY_ID_REQUEST = 'GET_AWARD_ATTACHMENT_BY_ID_REQUEST';
export const GET_AWARD_ATTACHMENT_BY_ID_FETCHING = 'GET_AWARD_ATTACHMENT_BY_ID_FETCHING';
export const GET_AWARD_ATTACHMENT_BY_ID_SUCCESS = 'GET_AWARD_ATTACHMENT_BY_ID_SUCCESS';
export const GET_AWARD_ATTACHMENT_BY_ID_FAILED = 'GET_AWARD_ATTACHMENT_BY_ID_FAILED';
export const UPDATE_AWARD_ATTACHMENT_REQUEST = 'UPDATE_AWARD_ATTACHMENT_REQUEST';
export const UPDATE_AWARD_ATTACHMENT_FETCHING = 'UPDATE_AWARD_ATTACHMENT_FETCHING';
export const UPDATE_AWARD_ATTACHMENT_SUCCESS = 'UPDATE_AWARD_ATTACHMENT_SUCCESS';
export const UPDATE_AWARD_ATTACHMENT_FAILED = 'UPDATE_AWARD_ATTACHMENT_FAILED';
export const DELETE_AWARD_ATTACHMENT_REQUEST = 'DELETE_AWARD_ATTACHMENT_REQUEST';
export const DELETE_AWARD_ATTACHMENT_FETCHING = 'DELETE_AWARD_ATTACHMENT_FETCHING';
export const DELETE_AWARD_ATTACHMENT_SUCCESS = 'DELETE_AWARD_ATTACHMENT_SUCCESS';
export const DELETE_AWARD_ATTACHMENT_FAILED = 'DELETE_AWARD_ATTACHMENT_FAILED';
// CERTIFICATE
export const ADD_CERTIFICATE_REQUEST = 'ADD_CERTIFICATE_REQUEST';
export const ADD_CERTIFICATE_FETCHING = 'ADD_CERTIFICATE_FETCHING';
export const ADD_CERTIFICATE_SUCCESS = 'ADD_CERTIFICATE_SUCCESS';
export const ADD_CERTIFICATE_FAILED = 'ADD_CERTIFICATE_FAILED';
export const GET_CERTIFICATE_REQUEST = 'GET_CERTIFICATE_REQUEST';
export const GET_CERTIFICATE_FETCHING = 'GET_CERTIFICATE_FETCHING';
export const GET_CERTIFICATE_SUCCESS = 'GET_CERTIFICATE_SUCCESS';
export const GET_CERTIFICATE_FAILED = 'GET_CERTIFICATE_FAILED';
export const GET_CERTIFICATE_BY_TYPE_REQUEST = 'GET_CERTIFICATE_BY_TYPE_REQUEST';
export const GET_CERTIFICATE_BY_TYPE_FETCHING = 'GET_CERTIFICATE_BY_TYPE_FETCHING';
export const GET_CERTIFICATE_BY_TYPE_SUCCESS = 'GET_CERTIFICATE_BY_TYPE_SUCCESS';
export const GET_CERTIFICATE_BY_TYPE_FAILED = 'GET_CERTIFICATE_BY_TYPE_FAILED';
export const UPDATE_CERTIFICATE_REQUEST = 'UPDATE_CERTIFICATE_REQUEST';
export const UPDATE_CERTIFICATE_FETCHING = 'UPDATE_CERTIFICATE_FETCHING';
export const UPDATE_CERTIFICATE_SUCCESS = 'UPDATE_CERTIFICATE_SUCCESS';
export const UPDATE_CERTIFICATE_FAILED = 'UPDATE_CERTIFICATE_FAILED';
export const DELETE_CERTIFICATE_REQUEST = 'DELETE_CERTIFICATE_REQUEST';
export const DELETE_CERTIFICATE_FETCHING = 'DELETE_CERTIFICATE_FETCHING';
export const DELETE_CERTIFICATE_SUCCESS = 'DELETE_CERTIFICATE_SUCCESS';
export const DELETE_CERTIFICATE_FAILED = 'DELETE_CERTIFICATE_FAILED';
// FORM SCIENCE DAY SURVEY
export const GET_FORM_SCIENCE_DAY_SURVEY_REQUEST = 'GET_FORM_SCIENCE_DAY_SURVEY_REQUEST';
export const GET_FORM_SCIENCE_DAY_SURVEY_FETCHING = 'GET_FORM_SCIENCE_DAY_SURVEY_FETCHING';
export const GET_FORM_SCIENCE_DAY_SURVEY_SUCCESS = 'GET_FORM_SCIENCE_DAY_SURVEY_SUCCESS';
export const GET_FORM_SCIENCE_DAY_SURVEY_FAILED = 'GET_FORM_SCIENCE_DAY_SURVEY_FAILED';
// FORM SCIENCE DAY
export const ADD_FORM_SCIENCE_DAY_REQUEST = 'ADD_FORM_SCIENCE_DAY_REQUEST';
export const ADD_FORM_SCIENCE_DAY_FETCHING = 'ADD_FORM_SCIENCE_DAY_FETCHING';
export const ADD_FORM_SCIENCE_DAY_SUCCESS = 'ADD_FORM_SCIENCE_DAY_SUCCESS';
export const ADD_FORM_SCIENCE_DAY_FAILED = 'ADD_FORM_SCIENCE_DAY_FAILED';
export const GET_FORM_SCIENCE_DAY_REQUEST = 'GET_FORM_SCIENCE_DAY_REQUEST';
export const GET_FORM_SCIENCE_DAY_FETCHING = 'GET_FORM_SCIENCE_DAY_FETCHING';
export const GET_FORM_SCIENCE_DAY_SUCCESS = 'GET_FORM_SCIENCE_DAY_SUCCESS';
export const GET_FORM_SCIENCE_DAY_FAILED = 'GET_FORM_SCIENCE_DAY_FAILED';
export const GET_FORM_SCIENCE_DAY_BY_ID_REQUEST = 'GET_FORM_SCIENCE_DAY_BY_ID_REQUEST';
export const GET_FORM_SCIENCE_DAY_BY_ID_FETCHING = 'GET_FORM_SCIENCE_DAY_BY_ID_FETCHING';
export const GET_FORM_SCIENCE_DAY_BY_ID_SUCCESS = 'GET_FORM_SCIENCE_DAY_BY_ID_SUCCESS';
export const GET_FORM_SCIENCE_DAY_BY_ID_FAILED = 'GET_FORM_SCIENCE_DAY_BY_ID_FAILED';
export const UPDATE_FORM_SCIENCE_DAY_REQUEST = 'UPDATE_FORM_SCIENCE_DAY_REQUEST';
export const UPDATE_FORM_SCIENCE_DAY_FETCHING = 'UPDATE_FORM_SCIENCE_DAY_FETCHING';
export const UPDATE_FORM_SCIENCE_DAY_SUCCESS = 'UPDATE_FORM_SCIENCE_DAY_SUCCESS';
export const UPDATE_FORM_SCIENCE_DAY_FAILED = 'UPDATE_FORM_SCIENCE_DAY_FAILED';
export const DELETE_FORM_SCIENCE_DAY_REQUEST = 'DELETE_FORM_SCIENCE_DAY_REQUEST';
export const DELETE_FORM_SCIENCE_DAY_FETCHING = 'DELETE_FORM_SCIENCE_DAY_FETCHING';
export const DELETE_FORM_SCIENCE_DAY_SUCCESS = 'DELETE_FORM_SCIENCE_DAY_SUCCESS';
export const DELETE_FORM_SCIENCE_DAY_FAILED = 'DELETE_FORM_SCIENCE_DAY_FAILED';
// FORM ACTIVITY
export const ADD_FORM_ACTIVITY_REQUEST = 'ADD_FORM_ACTIVITY_REQUEST';
export const ADD_FORM_ACTIVITY_FETCHING = 'ADD_FORM_ACTIVITY_FETCHING';
export const ADD_FORM_ACTIVITY_SUCCESS = 'ADD_FORM_ACTIVITY_SUCCESS';
export const ADD_FORM_ACTIVITY_FAILED = 'ADD_FORM_ACTIVITY_FAILED';
export const GET_FORM_ACTIVITY_BY_MEMBER_ID_REQUEST = 'GET_FORM_ACTIVITY_BY_MEMBER_ID_REQUEST';
export const GET_FORM_ACTIVITY_BY_MEMBER_ID_FETCHING = 'GET_FORM_ACTIVITY_BY_MEMBER_ID_FETCHING';
export const GET_FORM_ACTIVITY_BY_MEMBER_ID_SUCCESS = 'GET_FORM_ACTIVITY_BY_MEMBER_ID_SUCCESS';
export const GET_FORM_ACTIVITY_BY_MEMBER_ID_FAILED = 'GET_FORM_ACTIVITY_BY_MEMBER_ID_FAILED';
export const GET_FORM_ACTIVITY_BY_ID_REQUEST = 'GET_FORM_ACTIVITY_BY_ID_REQUEST';
export const GET_FORM_ACTIVITY_BY_ID_FETCHING = 'GET_FORM_ACTIVITY_BY_ID_FETCHING';
export const GET_FORM_ACTIVITY_BY_ID_SUCCESS = 'GET_FORM_ACTIVITY_BY_ID_SUCCESS';
export const GET_FORM_ACTIVITY_BY_ID_FAILED = 'GET_FORM_ACTIVITY_BY_ID_FAILED';
export const GET_ACTIVITY_DETAIL_REQUEST = 'GET_ACTIVITY_DETAIL_REQUEST';
export const GET_ACTIVITY_DETAIL_FETCHING = 'GET_ACTIVITY_DETAIL_FETCHING';
export const GET_ACTIVITY_DETAIL_SUCCESS = 'GET_ACTIVITY_DETAIL_SUCCESS';
export const GET_ACTIVITY_DETAIL_FAILED = 'GET_ACTIVITY_DETAIL_FAILED';
export const UPDATE_FORM_ACTIVITY_REQUEST = 'UPDATE_FORM_ACTIVITY_REQUEST';
export const UPDATE_FORM_ACTIVITY_FETCHING = 'UPDATE_FORM_ACTIVITY_FETCHING';
export const UPDATE_FORM_ACTIVITY_SUCCESS = 'UPDATE_FORM_ACTIVITY_SUCCESS';
export const UPDATE_FORM_ACTIVITY_FAILED = 'UPDATE_FORM_ACTIVITY_FAILED';
export const DELETE_FORM_ACTIVITY_REQUEST = 'DELETE_FORM_ACTIVITY_REQUEST';
export const DELETE_FORM_ACTIVITY_FETCHING = 'DELETE_FORM_ACTIVITY_FETCHING';
export const DELETE_FORM_ACTIVITY_SUCCESS = 'DELETE_FORM_ACTIVITY_SUCCESS';
export const DELETE_FORM_ACTIVITY_FAILED = 'DELETE_FORM_ACTIVITY_FAILED';
// COMPETITION
export const ADD_COMPETITION_REQUEST = 'ADD_COMPETITION_REQUEST';
export const ADD_COMPETITION_FETCHING = 'ADD_COMPETITION_FETCHING';
export const ADD_COMPETITION_SUCCESS = 'ADD_COMPETITION_SUCCESS';
export const ADD_COMPETITION_FAILED = 'ADD_COMPETITION_FAILED';
export const GET_COMPETITION_REQUEST = 'GET_COMPETITION_REQUEST';
export const GET_COMPETITION_FETCHING = 'GET_COMPETITION_FETCHING';
export const GET_COMPETITION_SUCCESS = 'GET_COMPETITION_SUCCESS';
export const GET_COMPETITION_FAILED = 'GET_COMPETITION_FAILED';
export const GET_COMPETITION_BY_ID_REQUEST = 'GET_COMPETITION_BY_ID_REQUEST';
export const GET_COMPETITION_BY_ID_FETCHING = 'GET_COMPETITION_BY_ID_FETCHING';
export const GET_COMPETITION_BY_ID_SUCCESS = 'GET_COMPETITION_BY_ID_SUCCESS';
export const GET_COMPETITION_BY_ID_FAILED = 'GET_COMPETITION_BY_ID_FAILED';
export const GET_COMPETITION_BY_MEMBER_ID_REQUEST = 'GET_COMPETITION_BY_MEMBER_ID_REQUEST';
export const GET_COMPETITION_BY_MEMBER_ID_FETCHING = 'GET_COMPETITION_BY_MEMBER_ID_FETCHING';
export const GET_COMPETITION_BY_MEMBER_ID_SUCCESS = 'GET_COMPETITION_BY_MEMBER_ID_SUCCESS';
export const GET_COMPETITION_BY_MEMBER_ID_FAILED = 'GET_COMPETITION_BY_MEMBER_ID_FAILED';
export const UPDATE_COMPETITION_REQUEST = 'UPDATE_COMPETITION_REQUEST';
export const UPDATE_COMPETITION_FETCHING = 'UPDATE_COMPETITION_FETCHING';
export const UPDATE_COMPETITION_SUCCESS = 'UPDATE_COMPETITION_SUCCESS';
export const UPDATE_COMPETITION_FAILED = 'UPDATE_COMPETITION_FAILED';
export const DELETE_COMPETITION_REQUEST = 'DELETE_COMPETITION_REQUEST';
export const DELETE_COMPETITION_FETCHING = 'DELETE_COMPETITION_FETCHING';
export const DELETE_COMPETITION_SUCCESS = 'DELETE_COMPETITION_SUCCESS';
export const DELETE_COMPETITION_FAILED = 'DELETE_COMPETITION_FAILED';
// PARTICIPANT
export const ADD_PARTICIPANT_REQUEST = 'ADD_PARTICIPANT_REQUEST';
export const ADD_PARTICIPANT_FETCHING = 'ADD_PARTICIPANT_FETCHING';
export const ADD_PARTICIPANT_SUCCESS = 'ADD_PARTICIPANT_SUCCESS';
export const ADD_PARTICIPANT_FAILED = 'ADD_PARTICIPANT_FAILED';
export const GET_PARTICIPANT_REQUEST = 'GET_PARTICIPANT_REQUEST';
export const GET_PARTICIPANT_FETCHING = 'GET_PARTICIPANT_FETCHING';
export const GET_PARTICIPANT_SUCCESS = 'GET_PARTICIPANT_SUCCESS';
export const GET_PARTICIPANT_FAILED = 'GET_PARTICIPANT_FAILED';
export const GET_PARTICIPANT_BY_ADMIN_ID_REQUEST = 'GET_PARTICIPANT_BY_ADMIN_ID_REQUEST';
export const GET_PARTICIPANT_BY_ADMIN_ID_FETCHING = 'GET_PARTICIPANT_BY_ADMIN_ID_FETCHING';
export const GET_PARTICIPANT_BY_ADMIN_ID_SUCCESS = 'GET_PARTICIPANT_BY_ADMIN_ID_SUCCESS';
export const GET_PARTICIPANT_BY_ADMIN_ID_FAILED = 'GET_PARTICIPANT_BY_ADMIN_ID_FAILED';
export const UPDATE_PARTICIPANT_REQUEST = 'UPDATE_PARTICIPANT_REQUEST';
export const UPDATE_PARTICIPANT_FETCHING = 'UPDATE_PARTICIPANT_FETCHING';
export const UPDATE_PARTICIPANT_SUCCESS = 'UPDATE_PARTICIPANT_SUCCESS';
export const UPDATE_PARTICIPANT_FAILED = 'UPDATE_PARTICIPANT_FAILED';
export const DELETE_PARTICIPANT_REQUEST = 'DELETE_PARTICIPANT_REQUEST';
export const DELETE_PARTICIPANT_FETCHING = 'DELETE_PARTICIPANT_FETCHING';
export const DELETE_PARTICIPANT_SUCCESS = 'DELETE_PARTICIPANT_SUCCESS';
export const DELETE_PARTICIPANT_FAILED = 'DELETE_PARTICIPANT_FAILED';
// FORM ACTIVITY RESPONSES
export const ADD_FORM_ACTIVITY_RESPONSES_REQUEST = 'ADD_FORM_ACTIVITY_RESPONSES_REQUEST';
export const ADD_FORM_ACTIVITY_RESPONSES_FETCHING = 'ADD_FORM_ACTIVITY_RESPONSES_FETCHING';
export const ADD_FORM_ACTIVITY_RESPONSES_SUCCESS = 'ADD_FORM_ACTIVITY_RESPONSES_SUCCESS';
export const ADD_FORM_ACTIVITY_RESPONSES_FAILED = 'ADD_FORM_ACTIVITY_RESPONSES_FAILED';
export const GET_FORM_ACTIVITY_RESPONSES_BY_ACTIVITY_ID_REQUEST =
  'GET_FORM_ACTIVITY_RESPONSES_BY_ACTIVITY_ID_REQUEST';
export const GET_FORM_ACTIVITY_RESPONSES_BY_ACTIVITY_ID_FETCHING =
  'GET_FORM_ACTIVITY_RESPONSES_BY_ACTIVITY_ID_FETCHING';
export const GET_FORM_ACTIVITY_RESPONSES_BY_ACTIVITY_ID_SUCCESS =
  'GET_FORM_ACTIVITY_RESPONSES_BY_ACTIVITY_ID_SUCCESS';
export const GET_FORM_ACTIVITY_RESPONSES_BY_ACTIVITY_ID_FAILED =
  'GET_FORM_ACTIVITY_RESPONSES_BY_ACTIVITY_ID_FAILED';
// FORM SCIENCE DAY RESPONSE
export const ADD_FORM_SCIENCE_DAY_RESPONSE_REQUEST = 'ADD_FORM_SCIENCE_DAY_RESPONSE_REQUEST';
export const ADD_FORM_SCIENCE_DAY_RESPONSE_FETCHING = 'ADD_FORM_SCIENCE_DAY_RESPONSE_FETCHING';
export const ADD_FORM_SCIENCE_DAY_RESPONSE_SUCCESS = 'ADD_FORM_SCIENCE_DAY_RESPONSE_SUCCESS';
export const ADD_FORM_SCIENCE_DAY_RESPONSE_FAILED = 'ADD_FORM_SCIENCE_DAY_RESPONSE_FAILED';
export const GET_FORM_SCIENCE_DAY_RESPONSE_REQUEST = 'GET_FORM_SCIENCE_DAY_RESPONSE_REQUEST';
export const GET_FORM_SCIENCE_DAY_RESPONSE_FETCHING = 'GET_FORM_SCIENCE_DAY_RESPONSE_FETCHING';
export const GET_FORM_SCIENCE_DAY_RESPONSE_SUCCESS = 'GET_FORM_SCIENCE_DAY_RESPONSE_SUCCESS';
export const GET_FORM_SCIENCE_DAY_RESPONSE_FAILED = 'GET_FORM_SCIENCE_DAY_RESPONSE_FAILED';
// AWARD LEVEL
export const ADD_AWARD_LEVEL_REQUEST = 'ADD_AWARD_LEVEL_REQUEST';
export const ADD_AWARD_LEVEL_FETCHING = 'ADD_AWARD_LEVEL_FETCHING';
export const ADD_AWARD_LEVEL_SUCCESS = 'ADD_AWARD_LEVEL_SUCCESS';
export const ADD_AWARD_LEVEL_FAILED = 'ADD_AWARD_LEVEL_FAILED';
export const GET_AWARD_LEVEL_REQUEST = 'GET_AWARD_LEVEL_REQUEST';
export const GET_AWARD_LEVEL_FETCHING = 'GET_AWARD_LEVEL_FETCHING';
export const GET_AWARD_LEVEL_SUCCESS = 'GET_AWARD_LEVEL_SUCCESS';
export const GET_AWARD_LEVEL_FAILED = 'GET_AWARD_LEVEL_FAILED';
export const UPDATE_AWARD_LEVEL_REQUEST = 'UPDATE_AWARD_LEVEL_REQUEST';
export const UPDATE_AWARD_LEVEL_FETCHING = 'UPDATE_AWARD_LEVEL_FETCHING';
export const UPDATE_AWARD_LEVEL_SUCCESS = 'UPDATE_AWARD_LEVEL_SUCCESS';
export const UPDATE_AWARD_LEVEL_FAILED = 'UPDATE_AWARD_LEVEL_FAILED';
export const DELETE_AWARD_LEVEL_REQUEST = 'DELETE_AWARD_LEVEL_REQUEST';
export const DELETE_AWARD_LEVEL_FETCHING = 'DELETE_AWARD_LEVEL_FETCHING';
export const DELETE_AWARD_LEVEL_SUCCESS = 'DELETE_AWARD_LEVEL_SUCCESS';
export const DELETE_AWARD_LEVEL_FAILED = 'DELETE_AWARD_LEVEL_FAILED';
// COMPETITION RESULT
export const ADD_COMPETITION_RESULT_REQUEST = 'ADD_COMPETITION_RESULT_REQUEST';
export const ADD_COMPETITION_RESULT_FETCHING = 'ADD_COMPETITION_RESULT_FETCHING';
export const ADD_COMPETITION_RESULT_SUCCESS = 'ADD_COMPETITION_RESULT_SUCCESS';
export const ADD_COMPETITION_RESULT_FAILED = 'ADD_COMPETITION_RESULT_FAILED';
export const GET_COMPETITION_RESULT_REQUEST = 'GET_COMPETITION_RESULT_REQUEST';
export const GET_COMPETITION_RESULT_FETCHING = 'GET_COMPETITION_RESULT_FETCHING';
export const GET_COMPETITION_RESULT_SUCCESS = 'GET_COMPETITION_RESULT_SUCCESS';
export const GET_COMPETITION_RESULT_FAILED = 'GET_COMPETITION_RESULT_FAILED';
export const GET_COMPETITION_RESULT_BY_ADMIN_ID_REQUEST =
  'GET_COMPETITION_RESULT_BY_ADMIN_ID_REQUEST';
export const GET_COMPETITION_RESULT_BY_ADMIN_ID_FETCHING =
  'GET_COMPETITION_RESULT_BY_ADMIN_ID_FETCHING';
export const GET_COMPETITION_RESULT_BY_ADMIN_ID_SUCCESS =
  'GET_COMPETITION_RESULT_BY_ADMIN_ID_SUCCESS';
export const GET_COMPETITION_RESULT_BY_ADMIN_ID_FAILED =
  'GET_COMPETITION_RESULT_BY_ADMIN_ID_FAILED';
export const GET_COMPETITION_RESULT_BY_MEMBER_ID_REQUEST =
  'GET_COMPETITION_RESULT_BY_MEMBER_ID_REQUEST';
export const GET_COMPETITION_RESULT_BY_MEMBER_ID_FETCHING =
  'GET_COMPETITION_RESULT_BY_MEMBER_ID_FETCHING';
export const GET_COMPETITION_RESULT_BY_MEMBER_ID_SUCCESS =
  'GET_COMPETITION_RESULT_BY_MEMBER_ID_SUCCESS';
export const GET_COMPETITION_RESULT_BY_MEMBER_ID_FAILED =
  'GET_COMPETITION_RESULT_BY_MEMBER_ID_FAILED';
export const GET_COMPETITION_RESULT_BY_OVERVIEW_REQUEST =
  'GET_COMPETITION_RESULT_BY_OVERVIEW_REQUEST';
export const GET_COMPETITION_RESULT_BY_OVERVIEW_FETCHING =
  'GET_COMPETITION_RESULT_BY_OVERVIEW_FETCHING';
export const GET_COMPETITION_RESULT_BY_OVERVIEW_SUCCESS =
  'GET_COMPETITION_RESULT_BY_OVERVIEW_SUCCESS';
export const GET_COMPETITION_RESULT_BY_OVERVIEW_FAILED =
  'GET_COMPETITION_RESULT_BY_OVERVIEW_FAILED';
export const GET_CHECK_COMPETITION_RESULT_REQUEST = 'GET_CHECK_COMPETITION_RESULT_REQUEST';
export const GET_CHECK_COMPETITION_RESULT_FETCHING = 'GET_CHECK_COMPETITION_RESULT_FETCHING';
export const GET_CHECK_COMPETITION_RESULT_SUCCESS = 'GET_CHECK_COMPETITION_RESULT_SUCCESS';
export const GET_CHECK_COMPETITION_RESULT_FAILED = 'GET_CHECK_COMPETITION_RESULT_FAILED';
export const UPDATE_COMPETITION_RESULT_REQUEST = 'UPDATE_COMPETITION_RESULT_REQUEST';
export const UPDATE_COMPETITION_RESULT_FETCHING = 'UPDATE_COMPETITION_RESULT_FETCHING';
export const UPDATE_COMPETITION_RESULT_SUCCESS = 'UPDATE_COMPETITION_RESULT_SUCCESS';
export const UPDATE_COMPETITION_RESULT_FAILED = 'UPDATE_COMPETITION_RESULT_FAILED';
export const UPDATE_CHECK_COMPETITION_RESULT_REQUEST = 'UPDATE_CHECK_COMPETITION_RESULT_REQUEST';
export const UPDATE_CHECK_COMPETITION_RESULT_FETCHING = 'UPDATE_CHECK_COMPETITION_RESULT_FETCHING';
export const UPDATE_CHECK_COMPETITION_RESULT_SUCCESS = 'UPDATE_CHECK_COMPETITION_RESULT_SUCCESS';
export const UPDATE_CHECK_COMPETITION_RESULT_FAILED = 'UPDATE_CHECK_COMPETITION_RESULT_FAILED';
export const DELETE_COMPETITION_RESULT_REQUEST = 'DELETE_COMPETITION_RESULT_REQUEST';
export const DELETE_COMPETITION_RESULT_FETCHING = 'DELETE_COMPETITION_RESULT_FETCHING';
export const DELETE_COMPETITION_RESULT_SUCCESS = 'DELETE_COMPETITION_RESULT_SUCCESS';
export const DELETE_COMPETITION_RESULT_FAILED = 'DELETE_COMPETITION_RESULT_FAILED';
// SEND MAIL
export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_FETCHING = 'SEND_EMAIL_FETCHING';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED';
// REPORT COMPEITION
export const GET_REPORT_COMPEITION_REQUEST = 'GET_REPORT_COMPEITION_REQUEST';
export const GET_REPORT_COMPEITION_FETCHING = 'GET_REPORT_COMPEITION_FETCHING';
export const GET_REPORT_COMPEITION_SUCCESS = 'GET_REPORT_COMPEITION_SUCCESS';
export const GET_REPORT_COMPEITION_FAILED = 'GET_REPORT_COMPEITION_FAILED';
// REPORT COMPEITION BY ID
export const GET_REPORT_COMPEITION_BY_ID_REQUEST = 'GET_REPORT_COMPEITION_BY_ID_REQUEST';
export const GET_REPORT_COMPEITION_BY_ID_FETCHING = 'GET_REPORT_COMPEITION_BY_ID_FETCHING';
export const GET_REPORT_COMPEITION_BY_ID_SUCCESS = 'GET_REPORT_COMPEITION_BY_ID_SUCCESS';
export const GET_REPORT_COMPEITION_BY_ID_FAILED = 'GET_REPORT_COMPEITION_BY_ID_FAILED';
// REPORT COMPEITION RESULT
export const GET_REPORT_COMPEITION_RESULT_REQUEST = 'GET_REPORT_COMPEITION_RESULT_REQUEST';
export const GET_REPORT_COMPEITION_RESULT_FETCHING = 'GET_REPORT_COMPEITION_RESULT_FETCHING';
export const GET_REPORT_COMPEITION_RESULT_SUCCESS = 'GET_REPORT_COMPEITION_RESULT_SUCCESS';
export const GET_REPORT_COMPEITION_RESULT_FAILED = 'GET_REPORT_COMPEITION_RESULT_FAILED';
// REPORT COMPEITION RESULT BY ID
export const GET_REPORT_COMPEITION_RESULT_BY_ID_REQUEST =
  'GET_REPORT_COMPEITION_RESULT_BY_ID_REQUEST';
export const GET_REPORT_COMPEITION_RESULT_BY_ID_FETCHING =
  'GET_REPORT_COMPEITION_RESULT_BY_ID_FETCHING';
export const GET_REPORT_COMPEITION_RESULT_BY_ID_SUCCESS =
  'GET_REPORT_COMPEITION_RESULT_BY_ID_SUCCESS';
export const GET_REPORT_COMPEITION_RESULT_BY_ID_FAILED =
  'GET_REPORT_COMPEITION_RESULT_BY_ID_FAILED';
// REPORT PARTICIPANT
export const GET_REPORT_PARTICIPANT_REQUEST = 'GET_REPORT_PARTICIPANT_REQUEST';
export const GET_REPORT_PARTICIPANT_FETCHING = 'GET_REPORT_PARTICIPANT_FETCHING';
export const GET_REPORT_PARTICIPANT_SUCCESS = 'GET_REPORT_PARTICIPANT_SUCCESS';
export const GET_REPORT_PARTICIPANT_FAILED = 'GET_REPORT_PARTICIPANT_FAILED';
// REPORT PARTICIPANT BY ADMIN ID
export const GET_REPORT_PARTICIPANT_BY_ADMIN_ID_REQUEST =
  'GET_REPORT_PARTICIPANT_BY_ADMIN_ID_REQUEST';
export const GET_REPORT_PARTICIPANT_BY_ADMIN_ID_FETCHING =
  'GET_REPORT_PARTICIPANT_BY_ADMIN_ID_FETCHING';
export const GET_REPORT_PARTICIPANT_BY_ADMIN_ID_SUCCESS =
  'GET_REPORT_PARTICIPANT_BY_ADMIN_ID_SUCCESS';
export const GET_REPORT_PARTICIPANT_BY_ADMIN_ID_FAILED =
  'GET_REPORT_PARTICIPANT_BY_ADMIN_ID_FAILED';
// REPORT COMPETITION AWARD
export const GET_REPORT_COMPETITION_AWARD_REQUEST = 'GET_REPORT_COMPETITION_AWARD_REQUEST';
export const GET_REPORT_COMPETITION_AWARD_FETCHING = 'GET_REPORT_COMPETITION_AWARD_FETCHING';
export const GET_REPORT_COMPETITION_AWARD_SUCCESS = 'GET_REPORT_COMPETITION_AWARD_SUCCESS';
export const GET_REPORT_COMPETITION_AWARD_FAILED = 'GET_REPORT_COMPETITION_AWARD_FAILED';
// REPORT COMPETITION AWARD BY ADMIN ID
export const GET_REPORT_COMPETITION_AWARD_BY_ADMIN_ID_REQUEST =
  'GET_REPORT_COMPETITION_AWARD_BY_ADMIN_ID_REQUEST';
export const GET_REPORT_COMPETITION_AWARD_BY_ADMIN_ID_FETCHING =
  'GET_REPORT_COMPETITION_AWARD_BY_ADMIN_ID_FETCHING';
export const GET_REPORT_COMPETITION_AWARD_BY_ADMIN_ID_SUCCESS =
  'GET_REPORT_COMPETITION_AWARD_BY_ADMIN_ID_SUCCESS';
export const GET_REPORT_COMPETITION_AWARD_BY_ADMIN_ID_FAILED =
  'GET_REPORT_COMPETITION_AWARD_BY_ADMIN_ID_FAILED';
// GET REPORT PROOF OF PAYMENT
export const GET_REPORT_PROOF_OF_PAYMENT_REQUEST = ' GET_REPORT_PROOF_OF_PAYMENT_REQUEST';
export const GET_REPORT_PROOF_OF_PAYMENT_FETCHING = ' GET_REPORT_PROOF_OF_PAYMENT_FETCHING';
export const GET_REPORT_PROOF_OF_PAYMENT_SUCCESS = ' GET_REPORT_PROOF_OF_PAYMENT_SUCCESS';
export const GET_REPORT_PROOF_OF_PAYMENT_FAILED = ' GET_REPORT_PROOF_OF_PAYMENT_FAILED';
